### ISSUE TITLE
Crash when FastWorkbench is not installed

### ISSUE THREAD

**Issue by josephcsible** [Lothrazar/Cyclic#1014]
Minecraft version & Mod Version:
Minecraft 1.12.2, Cyclic git build 690d9f2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
I typed `/gamemode c`, and the game crashed. This is a regression caused by commit e445345, which adds `event.getGui() instanceof GuiFastPlayerBench` to a code path that runs even if FastWorkbench isn't present.

Crash log (if any):
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/16/18 4:24 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: com/lothrazar/cyclicmagic/compat/fastbench/GuiFastPlayerBench
	at com.lothrazar.cyclicmagic.event.EventKeyInput.onGuiKeyboardEvent(EventKeyInput.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_EventKeyInput_onGuiKeyboardEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:511)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.lothrazar.cyclicmagic.compat.fastbench.GuiFastPlayerBench
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: shadows/fastbench/gui/GuiFastBench
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more
Caused by: java.lang.ClassNotFoundException: shadows.fastbench.gui.GuiFastBench
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.lothrazar.cyclicmagic.event.EventKeyInput.onGuiKeyboardEvent(EventKeyInput.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_EventKeyInput_onGuiKeyboardEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:511)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiChat

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['josephcsible'/187, l='MpServer', x=254.50, y=65.00, z=212.35]]
	Chunk stats: MultiplayerChunkCache: 573, 573
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,212), Chunk: (at 4,4,4 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13526 game time, 29369 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 37 total; [EntityPig['Pig'/129, l='MpServer', x=334.50, y=66.00, z=228.32], EntityPlayerSP['josephcsible'/187, l='MpServer', x=254.50, y=65.00, z=212.35], EntityPig['Pig'/71, l='MpServer', x=186.27, y=78.00, z=221.57], EntityPig['Pig'/72, l='MpServer', x=182.55, y=78.00, z=210.06], EntityCow['Cow'/73, l='MpServer', x=190.08, y=79.00, z=208.55], EntityPig['Pig'/74, l='MpServer', x=182.03, y=80.00, z=215.55], EntityCow['Cow'/75, l='MpServer', x=183.22, y=80.00, z=216.58], EntityPig['Pig'/76, l='MpServer', x=189.06, y=80.00, z=209.55], EntityCow['Cow'/79, l='MpServer', x=194.69, y=77.00, z=217.71], EntityCow['Cow'/80, l='MpServer', x=190.76, y=80.00, z=219.54], EntityPig['Pig'/81, l='MpServer', x=222.72, y=63.00, z=217.80], EntityBat['Bat'/84, l='MpServer', x=232.49, y=15.03, z=206.19], EntityPig['Pig'/89, l='MpServer', x=238.68, y=66.00, z=177.50], EntityPig['Pig'/90, l='MpServer', x=240.50, y=63.00, z=250.21], EntityPig['Pig'/91, l='MpServer', x=253.55, y=77.00, z=251.35], EntityPig['Pig'/92, l='MpServer', x=255.54, y=79.00, z=251.24], EntityPig['Pig'/93, l='MpServer', x=255.50, y=78.00, z=249.30], EntityPig['Pig'/94, l='MpServer', x=255.78, y=81.00, z=262.27], EntityBat['Bat'/98, l='MpServer', x=268.54, y=43.10, z=133.71], EntityBat['Bat'/99, l='MpServer', x=253.34, y=18.03, z=178.61], EntityBat['Bat'/100, l='MpServer', x=259.55, y=17.01, z=176.00], EntityPig['Pig'/101, l='MpServer', x=259.50, y=65.00, z=184.20], EntityCow['Cow'/102, l='MpServer', x=261.42, y=64.00, z=223.83], EntityBat['Bat'/103, l='MpServer', x=267.25, y=42.10, z=241.25], EntityPig['Pig'/104, l='MpServer', x=270.49, y=80.00, z=250.25], EntityPig['Pig'/105, l='MpServer', x=264.50, y=81.00, z=268.50], EntityPig['Pig'/106, l='MpServer', x=271.49, y=81.00, z=262.78], EntityPig['Pig'/107, l='MpServer', x=256.67, y=81.00, z=260.51], EntityBat['Bat'/108, l='MpServer', x=291.51, y=29.41, z=240.53], EntityPig['Pig'/110, l='MpServer', x=300.59, y=71.00, z=202.25], EntityCow['Cow'/111, l='MpServer', x=293.18, y=68.00, z=192.50], EntityCow['Cow'/112, l='MpServer', x=293.45, y=71.00, z=206.19], EntityPig['Pig'/113, l='MpServer', x=294.80, y=73.00, z=214.26], EntityPig['Pig'/120, l='MpServer', x=308.33, y=73.00, z=203.50], EntityPig['Pig'/124, l='MpServer', x=335.25, y=69.00, z=153.53], EntityPig['Pig'/125, l='MpServer', x=334.50, y=67.00, z=216.75], EntityPig['Pig'/126, l='MpServer', x=333.78, y=72.00, z=269.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 947800416 bytes (903 MB) / 2510815232 bytes (2394 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version                 | Source                                  | Signature                                |
	|:------ |:------------------ |:----------------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2                  | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                | 9.42                    | minecraft.jar                           | None                                     |
	| LCHIJA | FML                | 8.0.99.99               | forge-1.12.2-14.23.5.2796.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2796            | forge-1.12.2-14.23.5.2796.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei                | 4.14.3.238              | jei_1.12.2-4.14.3.238.jar               | None                                     |
	| LCHIJA | cyclicmagic        | 1.17.11                 | Cyclic-1.12.2-1.17.11.jar               | None                                     |
	| LCHIJA | guideapi           | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar             | None                                     |
	| LCHIJA | mekanism           | 1.12.2-9.4.13.homebaked | MekanismAll-1.12.2-9.4.13.homebaked.jar | None                                     |
	| LCHIJA | mekanismgenerators | 9.4.11                  | MekanismAll-1.12.2-9.4.13.homebaked.jar | None                                     |
	| LCHIJA | mekanismtools      | 9.4.11                  | MekanismAll-1.12.2-9.4.13.homebaked.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4771' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: forge-14.23.5.2796
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 22.20.16.4771, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
```

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/cyclic/files/2649312
